<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="characteristics"
    nsURI="http://www.palladiosimulator.org/pcm/characteristics/1.0"
    nsPrefix="characteristics">
  <eAnnotations
      source="http://www.eclipse.org/emf/2002/Ecore">
    <details
        key="invocationDelegates"
        value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details
        key="settingDelegates"
        value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details
        key="validationDelegates"
        value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eSubpackages
      name="manifestation"
      nsURI="http://www.palladiosimulator.org/pcm/characteristics/manifestation/1.0"
      nsPrefix="manifestation">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CharacteristicManifestationFilter"
        abstract="true"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="DerivedCharacteristicManifestationType"
        abstract="true"
        eSuperTypes="#//manifestation/ManifestationType">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="requiredCharacterizations"
          upperBound="-1"
          eType="#//manifestation/CharacterizationRequirement"
          containment="true"
          eOpposite="#//manifestation/CharacterizationRequirement/derivedManifestation"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="StaticManifestationType"
        abstract="true"
        eSuperTypes="#//manifestation/ManifestationType"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ManifestationType"
        abstract="true"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ManifestationTypeRepository">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="types"
          upperBound="-1"
          eType="#//manifestation/ManifestationType"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ProbabilisticManifestationType"
        eSuperTypes="#//manifestation/ManifestationType"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CharacterizationRequirement">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="derivedManifestation"
          eType="#//manifestation/DerivedCharacteristicManifestationType"
          eOpposite="#//manifestation/DerivedCharacteristicManifestationType/requiredCharacterizations"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages
      name="instance"
      nsURI="http://www.palladiosimulator.org/pcm/characteristics/instance/1.0"
      nsPrefix="instance">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CharacteristicManifestation"
        abstract="true">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="manifestation"
          lowerBound="1"
          eType="#//manifestation/ManifestationType"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="valueType"
          lowerBound="1"
          eType="#//valuetype/ValueType"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Characterizable"
        abstract="true">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="characteristics"
          upperBound="-1"
          eType="#//instance/CharacteristicManifestation"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages
      name="characteristic"
      nsURI="http://www.palladiosimulator.org/pcm/characteristics/characteristic/1.0"
      nsPrefix="characteristic">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Characteristic"
        abstract="true"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="valueType"
          eType="#//valuetype/ValueType"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CharacteristicApplicationRule"
        abstract="true">
      <eOperations
          name="isApplicableTo"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters
            name="element"
            eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eOperations>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="validCharacteristics"
          lowerBound="1"
          upperBound="-1"
          eType="#//characteristic/Characteristic"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CharacteristicCatalog">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="characteristics"
          upperBound="-1"
          eType="#//characteristic/Characteristic"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="profiles"
          upperBound="-1"
          eType="#//characteristic/CharacteristicProfile"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CharacteristicProfile">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="applicationrules"
          upperBound="-1"
          eType="#//characteristic/CharacteristicApplicationRule"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages
      name="valuetype"
      nsURI="http://www.palladiosimulator.org/pcm/characteristics/valuetype/1.0"
      nsPrefix="valuetype">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ValueType"
        abstract="true"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eOperations
          name="getProperty">
        <eGenericType
            eClassifier="#//valuetype/Optional">
          <eTypeArguments
              eTypeParameter="#//valuetype/ValueType/getProperty/P"/>
        </eGenericType>
        <eTypeParameters
            name="P">
          <eBounds
              eClassifier="#//valuetype/ValueTypeProperty"/>
        </eTypeParameters>
        <eParameters
            name="propertyType">
          <eGenericType
              eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments
                eTypeParameter="#//valuetype/ValueType/getProperty/P"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="isParametric"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          transient="true"
          derived="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="properties"
          upperBound="-1"
          eType="#//valuetype/ValueTypeProperty"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="name"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="EDataTypeValueType"
        eSuperTypes="#//valuetype/BaseValueType">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="baseType"
          eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDataType"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ComposedValueType"
        eSuperTypes="#//valuetype/ValueType">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="nestedTypes"
          lowerBound="1"
          upperBound="-1"
          eType="#//valuetype/ValueType"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="BaseValueType"
        eSuperTypes="#//valuetype/ValueType"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="EnumValueType"
        eSuperTypes="#//valuetype/BaseValueType #//valuetype/ExplicitSetValueType"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ValueTypeProperty"
        abstract="true"
        interface="true"/>
    <eClassifiers
        xsi:type="ecore:EDataType"
        name="Optional"
        instanceTypeName="Optional">
      <eTypeParameters
          name="T"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ExplicitSetValueType"
        abstract="true">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="explicitValues"
          eType="#//instance/CharacteristicManifestation"
          containment="true"/>
    </eClassifiers>
    <eSubpackages
        name="properties"
        nsURI="http://www.palladiosimulator.org/pcm/characteristics/valuetype/properties/1.0"
        nsPrefix="properties">
      <eClassifiers
          xsi:type="ecore:EClass"
          name="OrderedValueType"
          abstract="true"
          interface="true">
        <eOperations
            name="compare"
            eType="#//instance/CharacteristicManifestation">
          <eParameters
              name="first"
              eType="#//instance/CharacteristicManifestation"/>
          <eParameters
              name="second"
              eType="#//instance/CharacteristicManifestation"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers
          xsi:type="ecore:EClass"
          name="FiniteSetValueType"
          abstract="true"
          interface="true">
        <eOperations
            name="values">
          <eGenericType
              eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
            <eTypeArguments
                eClassifier="#//instance/CharacteristicManifestation"/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
