<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EditProperties" nsURI="http://www.mdsd.tools/characteristics/valuetype/editProperties/1.0"
    nsPrefix="editproperties">
  <eClassifiers xsi:type="ecore:EClass" name="CustomLabelProvider" eSuperTypes="../../tools.mdsd.characteristics.model/model/characteristics.ecore#//valuetype/ValueTypeProperty">
    <eOperations name="getLabelProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IItemLabelProvider" instanceClassName="org.eclipse.emf.edit.provider.IItemLabelProvider"
      serializable="false"/>
</ecore:EPackage>
